version: '3.8'
services:
  mariadb:
    image: mariadb
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kplus
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - '3306:3306'
  # app:
  #   build: .
  #   restart: on-failure
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - '8080:8080'